---
title: "Problem Set 1"
author: "Cort Breuer"
date: "09/08/19"
output:
  html_document: default
  pdf_document: default
subtitle: ENGRD 2700
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, packages, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(gridExtra)
theme_set(theme_bw())
```

## Question 1

```{r, question 1 setup}
quartet <- read.csv("Data/Quartet.csv")
```

### Part A

$\text{X1 Sample Mean} = \frac{10+8+13+9+11+14+6+4+12+7+5}{11}=9$

$\text{X1 Sample Median} = 4,5,6,7,8,\textbf{9},10,11,12,13,14 = 9$

$\text{X1 Sample Standard Deviation} = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}{{(x_{i}-\bar{x}}})^2} = \sqrt{\frac{1}{10}[(4-9)^2+...(14-9)^2]} = \sqrt{11} = 3.32$

```{R, summary statistics}
colNames <- c("X1", "X2", "X3", "X4", "Y1", "Y2", "Y3", "Y4")

quartetMean <- apply(quartet, 2, mean)
quartetMedian <- apply(quartet, 2, median)
quartetSD <- apply(quartet, 2, sd)

summaryTable <- tibble(colNames, quartetMean, quartetMedian, quartetSD) %>% rename(Column = colNames, "Sample Mean" = quartetMean, "Sample Median" = quartetMedian, "Sample Standard Deviation" = quartetSD) %>% mutate_if(is.numeric, round, digits = 2)

kable(summaryTable) %>% kable_styling(bootstrap_options = c("striped", "hover"))
```

### Part B

### Part C

```{r, quartet scatter plots}
p1 <- ggplot(data = quartet, aes(x = x1, y = y1)) + geom_point(size = 3) + xlim(0, 19) + ylim(0, 15)
p2 <- ggplot(data = quartet, aes(x = x2, y = y2)) + geom_point(size = 3) + xlim(0, 19) + ylim(0, 15)
p3 <- ggplot(data = quartet, aes(x = x3, y = y3)) + geom_point(size = 3) + xlim(0, 19) + ylim(0, 15)
p4 <- ggplot(data = quartet, aes(x = x4, y = y4)) + geom_point(size = 3) + xlim(0, 19) + ylim(0, 15)

grid.arrange(p1, p2, p3, p4)
```

### Part D

### Part E

## Question 2

```{r, question 2 setup}
countyData <- read.csv("Data/CountyData.csv")
countyData <- as_tibble(countyData)
```

### Part A

```{r, foreign language histogram}
ggplot(data = countyData) + geom_histogram(mapping = aes(foreign_spoken_at_home), binwidth = 5) + labs(x = "Percent of Residents Who Speak a Foreign Language at Home", y = "Number of Counties") + theme(panel.border = element_rect(colour = "black", fill=NA, size=1))
```

### Part B

```{r, median federal spennding}
median(countyData$fed_spending, na.rm = TRUE)
```

### Part C

```{r, poverty and education plot}
ggplot(data = countyData) + geom_point(mapping = aes(x = bachelors, y = poverty)) + xlim(0, 80) + ylim(0, 80) + coord_fixed() + ggtitle("Poverty vs. Bachelors")

par(pty = "s")

plot(countyData$bachelors, countyData$poverty, xlim = c(0, 80), ylim = c(0, 80), main = "Poverty vs. Bachelors", xlab = "Percent of County with Bachelors Degrees", ylab = "Percent of County Below Poverty Line")
```

### Part D

## Question 3

### Part A

### Part B

### Part C

## Question 4

### Part A

### Part B

$$z_{i} = \frac{x_{i}-\overline{x}}{s_{x}}$$