---
title: "Problem Set 2"
author: "Cort Breuer"
date: "09/18/19"
output:
  html_document: default
  pdf_document: default
subtitle: ENGRD 2700
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

#### Part A

Dividing 12 people into 2 groups is unordered sampling without replacment, requiring n choose k, divided by two to avoid complement groups. 

$Samplese = \frac{1}{2} C_{6, 12} = \frac{1}{2}\binom{12}{6} = \frac{1}{2} \cdot \frac{n!}{k!(n-k)!} = \frac{1}{2} \cdot \frac{12!}{6!(6)!} = 462$

#### Part B

Dividing 12 people into 3 groups is again unordered sampling without replacement, requring n choose k, divided by the number of group complements, 3!. 

$Samples = \frac{1}{3!} C_{4, 12} C_{4, 8} = \frac{1}{3!} \binom{12}{4} \binom{8}{4}= = \frac{1}{3!} \cdot \frac{12!}{4!(8)!} \frac{8!}{4!(4)!}= 5775$

#### Part C

$\binom{12}{12} + \binom{12}{11} + \binom{12}{10} + \binom{12}{9} + \binom{12}{8} + \binom{12}{7} + \frac{1}{2}\binom{12}{6}$

## Question 2

#### Part A

Alice, by computing $\binom{8}{3} \binom{5}{2} \cdot 3! = 3360$, is likely breaking the 8 slots by the types of letters that can be chosen. First she finds the number of ways to fill 3 of the 8 slots with E's. Then the number of ways to fill 2 slots with N's, and finally the last 3 slots with the 3 unique letters left. 

####Part B

assign the 8 letters, divide by the different ways of arranging the same E's,  then divide by the ways to arrange the  same N's

#### Part C

$\frac{1}{8} \binom{8}{3} \binom{5}{2} 3! = 420$

## Question 3

#### Part A

The number of 4 person teams that can be made from 36 MEng students is based on unordered sampling without replacement. Thus $C_{4,36} = \binom{n}{k} = \binom{36}{4} = \frac{36!}{4! \cdot 32!} = 58905$ so there are a total of 58905 possible teams.

#### Part B

Finding the numbere of possible 4 person teams consisting of 2 men and 2 women when there are 16 men and 20 women involves unordered sampling without replacement of gender pairs and the multiplication rule for making full teams. Thus the ways to make pairs of men is $C_{2,16} = \binom{n}{k} = \binom{16}{2} = \frac{16!}{2! \cdot 14!} = 120$ while the ways to make pairs of women is $C_{2,20} = \binom{n}{k} = \binom{20}{2} = \frac{20!}{2! \cdot 18!} = 190$. The ways to make teams of 4 incorporating 2 men and 2 women involves multiplying the possibilities of pairs of men and women, $C_{2,20} \cdot C_{2,16} = 120 \cdot 190 = 22800$, so there are a total of 22800 teams possible.

## Question 4

A~1~ denotes the event someone likes football
A~2~ denotes the event someone likes basketball
A~3~ denotes the event someone likes swimming



#### Part A





#### Part B

#### Part C

#### Part D

#### Part E

## Question 5

Elevator A is down 35% of the time, elevator 30%, and elevator C 10%. 

#### Part A

- All 3 elevators are down is given by $A \cap B \cap C$

- Only elevator A is down is given by $(B \cup C)^c$

- None of the elevators are down is given by $(A \cup B \cup C)^c$

- At least one elevator is down is given by $A \cup B \cup C$

- EExactly one elevator is down is given by 

#### Part B

The max of $P(A \cup B \cup C)$ is the sum of probabilities, $P = 35 + 30 + 10 = 75%$, while 



#### Part C

$P(A \cap B) = .2$, $P(A \cup B) = P(A) + P(B) - P(A \cap B)$ so $P(A \cup B) = .35 + .3 + .2 = \text{.85 or 85%}$.

#### Part D

## Question 6

Number of ways to assign 15 pumps to 8 tanks, where $d(k,n)$ is the number of ways to assign k pumps to n tanks. 

#### Part A

$d(k,n) = 0$ for $n > k \geq 1$ since if the number of tanks is greater than the number of pumps, not every tank will recive a pump, which violates the goal of each thank receiving at least one pump.

#### Part B

$d(k,k) = k!$ for all $k \geq 1$ since once a pump is assigned to a tank, the number of possibilities is then k-1, and once a second is assigned the number of possibilities becomes k-2. As this progresses, where a pump is assigned one at a time, the number of possible assignments decreases by one, creating a factorial starting at k, thus k! arrangements.

#### Part C

$d(k,1) = 2^k - 1$ for all $k \geq 1$ since with just a single tank, anywhere from just one of the k pumps to all of the k pumps can be assigned, which amounts to ordered sampling with replacment without assignment of 0 pumps. This is because any combination of pumps can be assigned, where the number of combinations is $n^k$ except the case where none are assigned is not possible so one combination must be remove from the total. 

#### Part D

#### Part E

#### Part F